[package]
name = "client-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tungstenite = { version = "0.26.1", features = [
    "rustls-tls-native-roots",
] }
futures-util = "0.3.31"
tokio = { version = "1.43.0", features = [
    "rt-multi-thread",
    "macros",
    "io-std",
], default-features = false }
futures-channel = "0.3.31"
clap = { version = "4.5.29", features = ["std"], default-features = false }
rustls = { version = "0.23.23", features = ["ring", "std", "tls12"], default-features = false }

[profile.release]
opt-level = 'z'
lto = "fat"
codegen-units = 1
incremental = false
panic = "abort"
strip = "symbols"
debug-assertions = false
overflow-checks = false
