[package]
name = "client-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tungstenite = { version = "0.26.1", features = ["rustls-tls-webpki-roots"] }
futures-util = "0.3.31"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "io-std"] }
futures-channel = "0.3.31"
clap = "4.5.29"
rustls = "0.23.23"
tokio-rustls = "0.26.1"
webpki-roots = "0.26.8"
url = "2.5.4"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
incremental = false
panic = "unwind"
strip = "symbols"
debug-assertions = false
overflow-checks = false
